In [10]:
lines = []

with open("input6.txt") as file:
    for line_n, line in enumerate(file):
        if line_n <= 3:
            line = line.replace(" ", ",")
            line = line.split(",")
            line = [int(x) for x in line if len(x)>0]
            lines.append(line)
        else:
            line = line.replace(" ", ",")
            line = line.split(",")
            line = [x for x in line if len(x)>0]
            operations = line


In [41]:
import numpy as np

numbers = np.matrix(lines).T


NameError: name 'lines' is not defined

In [28]:
complete_sum = 0
for number_row, operation in zip(numbers, operations):
    number_row = np.squeeze(list(number_row))
    print(number_row)
    print(operation)
    if operation == "+":
        complete_sum += sum(number_row)
    elif operation == "*":
        tmp = number_row[0]
        for number in number_row[1:]:
            tmp *= number
        complete_sum += tmp


[132 985 235  25]
*
[  9   6 385 289]
*
[56 64 51 75]
*
[13 55 48  7]
+
[68 95 28 99]
*
[446 671  39  98]
*
[884 761 236 258]
*
[12 31 44 93]
+
[413 116 581 572]
+
[6126 6625  251   55]
+
[ 118  127  728 5456]
+
[ 89 977 338 537]
+
[73 35 82 26]
+
[4858   21   24    4]
+
[534 981  46  88]
*
[74 93  2  8]
+
[627 485 697  87]
+
[ 3 37 21 57]
+
[7823  532  149  722]
+
[ 4  8 75 85]
*
[ 32  68 547 597]
+
[879 914  63   1]
*
[83 98 72 23]
*
[ 67 727 523 466]
+
[ 442 8764 9368 9192]
+
[ 85 933 169 899]
*
[839 476  81   6]
*
[71 39 83 79]
+
[74 14 89 33]
+
[314 744 792  98]
+
[  8  79 583 295]
+
[  8  35  83 251]
+
[19 95 86 67]
*
[  1 497 557 815]
+
[627 376 778  81]
+
[  4   8 114 923]
*
[24 29 13 94]
*
[73 11 18  7]
+
[ 9 29 51 12]
*
[18 38  5  8]
*
[65 37 16 53]
*
[19 13  7  1]
*
[  56 5853 9662 1727]
+
[36 62 57  8]
+
[ 53 854 327 115]
+
[ 57 545 322 815]
*
[ 66 569 989 333]
+
[ 947 4948 7994 9452]
+
[919 892 691 625]
+
[422 287 995  73]
*
[ 6  5  9 22]
*
[937 951 174  13]
*
[564 473 267

In [29]:
complete_sum

np.int64(6100348226985)

In [47]:

all_numbers = []
operations = []
numbers = []

whatever = []

for i in range(0, 3724):
    with open("input6.txt") as file:
        tmp = []
        for line in file:
            tmp.append(line[i])
        whatever.append(tmp)



for element in whatever:
    if all([x==" " for x in element]):
        all_numbers.append(numbers)
        numbers = []
        continue
    number = []
    for character in element:
        if character.isdigit():
            number.append(character)
        elif character in ["*", "+"]:
            operations.append(character)

    numbers.append("".join(number))
            

        

In [48]:
complete_sum = 0
for number_row, operation in zip(all_numbers, operations):
    number_row = np.squeeze(list(number_row))
    number_row = [int(x) for x in number_row]
    print(number_row)
    print(operation)
    if operation == "+":
        complete_sum += sum(number_row)
        print(sum(number_row))
    elif operation == "*":
        tmp = number_row[0]
        for number in number_row[1:]:
            tmp *= number
        complete_sum += tmp
        print(tmp)

[1922, 3835, 255]
*
1879571850
[9632, 88, 59]
*
50009344
[5657, 6415]
*
36289655
[1547, 358]
+
1905
[6929, 8589]
*
59513181
[4639, 4798, 61]
*
1357733242
[8722, 8635, 4168]
*
313910710960
[1349, 2143]
+
3492
[4155, 1187, 3612]
+
8954
[6625, 1655, 221, 65]
+
8566
[1175, 1224, 8785, 6]
+
11190
[8935, 9733, 787]
+
19455
[7382, 3526]
+
10908
[4224, 814, 5, 8]
+
5051
[59, 3848, 4168]
*
946269376
[79, 4328]
+
4407
[6468, 2897, 757]
+
10122
[325, 3717]
+
4042
[7, 8517, 2342, 3292]
+
14158
[4878, 55]
*
268290
[3655, 2849, 77]
+
6581
[89, 716, 9431]
*
600981044
[8972, 3823]
*
34299956
[6754, 7226, 736]
+
14716
[4899, 4731, 2669, 482]
+
12781
[8918, 5369, 399]
*
19104416058
[84, 378, 9616]
*
305327232
[7387, 1939]
+
9326
[7183, 4493]
+
11676
[3779, 1498, 442]
+
5719
[8752, 989, 35]
+
9776
[8382, 535, 1]
+
8918
[1986, 9567]
*
19000062
[458, 951, 1775]
+
3184
[6378, 2771, 768]
+
9917
[19, 12, 4843]
*
1104204
[2219, 4934]
*
10948546
[711, 3187]
+
3898
[9251, 912]
*
8436912
[13, 8858]
*
115154
[6315

In [49]:
complete_sum += 4538 * 7968

In [50]:
complete_sum

12377473011151